annotation: &id001 {}
bin: /Users/alynch/projects/multiomics/kladi/kladi/genome_tracks/bin
cis_models_ammecr1:
  genome_file: /Users/alynch/genomes/mm10/mm10.genome
cis_models_ccser1:
  genome_file: /Users/alynch/genomes/mm10/mm10.genome
coverage_b_matrix:
  fragment_file: ../datasets/share-seq/notebooks/tracks_data/GSM4156597_skin.late.anagen.atac.fragments.sorted.bed
  genome_file: /Users/alynch/genomes/mm10/mm10.genome
  norm_constant: 10000.0
coverage_c_branch:
  fragment_file: ../datasets/share-seq/notebooks/tracks_data/GSM4156597_skin.late.anagen.atac.fragments.sorted.bed
  genome_file: /Users/alynch/genomes/mm10/mm10.genome
  norm_constant: 10000.0
coverage_e_cortex:
  fragment_file: ../datasets/share-seq/notebooks/tracks_data/GSM4156597_skin.late.anagen.atac.fragments.sorted.bed
  genome_file: /Users/alynch/genomes/mm10/mm10.genome
  norm_constant: 10000.0
scalebar: *id001
sources:
  datasetsshare_seqnotebookstracks_datafiltered_genesbed: ../datasets/share-seq/notebooks/tracks_data/filtered_genes.bed
  datasetsshare_seqnotebookstracks_datagsm4156597_skinlateanagenatacfragmentssortedbed: ../datasets/share-seq/notebooks/tracks_data/GSM4156597_skin.late.anagen.atac.fragments.sorted.bed
  datashareseq: data/shareseq/
  none: none
targets:
- data/shareseq/
- ../datasets/share-seq/notebooks/tracks_data/filtered_genes.bed
- data/shareseq/trackdir/AMMECR1/cis_models_ccser1-cis_model-none-cis_model.bigwig
- data/shareseq/trackdir/AMMECR1/cis_models_ammecr1-cis_model-none-cis_model.bigwig
- data/shareseq/trackdir/AMMECR1/coverage_b_matrix-fragment_coverage-datasetsshare_seqnotebookstracks_datagsm4156597_skinlateanagenatacfragmentssortedbed-pileup.bigwig
- data/shareseq/trackdir/AMMECR1/coverage_c_branch-fragment_coverage-datasetsshare_seqnotebookstracks_datagsm4156597_skinlateanagenatacfragmentssortedbed-pileup.bigwig
- data/shareseq/trackdir/AMMECR1/coverage_e_cortex-fragment_coverage-datasetsshare_seqnotebookstracks_datagsm4156597_skinlateanagenatacfragmentssortedbed-pileup.bigwig
