bin: /home/allen/projects/liulab/multiomics/kladi/Kladi/kladi/genome_tracks/bin
cismodel_al5910432:
  genome_file: /home/allen/genomes/hg38/hg38.genome
cismodel_cd74:
  genome_file: /home/allen/genomes/hg38/hg38.genome
cismodel_dzank1:
  genome_file: /home/allen/genomes/hg38/hg38.genome
cismodel_il4r:
  genome_file: /home/allen/genomes/hg38/hg38.genome
cismodel_pax5:
  genome_file: /home/allen/genomes/hg38/hg38.genome
coverage_b_cell:
  fragment_file: data/bcell_lymphoma/trackdata/lymph_node_lymphoma_14k_atac_fragments.tsv.gz
  genome_file: /home/allen/genomes/hg38/hg38.genome
  norm_constant: 10000.0
coverage_lymphoma:
  fragment_file: data/bcell_lymphoma/trackdata/lymph_node_lymphoma_14k_atac_fragments.tsv.gz
  genome_file: /home/allen/genomes/hg38/hg38.genome
  norm_constant: 10000.0
coverage_macrophage:
  fragment_file: data/bcell_lymphoma/trackdata/lymph_node_lymphoma_14k_atac_fragments.tsv.gz
  genome_file: /home/allen/genomes/hg38/hg38.genome
  norm_constant: 10000.0
coverage_t_cell:
  fragment_file: data/bcell_lymphoma/trackdata/lymph_node_lymphoma_14k_atac_fragments.tsv.gz
  genome_file: /home/allen/genomes/hg38/hg38.genome
  norm_constant: 10000.0
factorhits_46138: {}
factorhits_51245: {}
factorhits_59437: {}
genes: &id001 {}
scalebar: *id001
sources:
  databcell_lymphoma: data/bcell_lymphoma/
  databcell_lymphomatrackdatalymph_node_lymphoma_14k_atac_fragmentstsvgz: data/bcell_lymphoma/trackdata/lymph_node_lymphoma_14k_atac_fragments.tsv.gz
  homeallengenomeshg38hg38_annotation_canonicalbed: /home/allen/genomes/hg38/hg38_annotation_canonical.bed
  none: none
targets:
- data/bcell_lymphoma/
- /home/allen/genomes/hg38/hg38_annotation_canonical.bed
- data/bcell_lymphoma/trackdata/pax5/cismodel_pax5-cis_model-none-cis_model.bigwig
- data/bcell_lymphoma/trackdata/pax5/cismodel_il4r-cis_model-none-cis_model.bigwig
- data/bcell_lymphoma/trackdata/pax5/cismodel_cd74-cis_model-none-cis_model.bigwig
- data/bcell_lymphoma/trackdata/pax5/cismodel_al5910432-cis_model-none-cis_model.bigwig
- data/bcell_lymphoma/trackdata/pax5/cismodel_dzank1-cis_model-none-cis_model.bigwig
- data/bcell_lymphoma/trackdata/pax5/coverage_b_cell-fragment_coverage-databcell_lymphomatrackdatalymph_node_lymphoma_14k_atac_fragmentstsvgz-pileup.bigwig
- data/bcell_lymphoma/trackdata/pax5/coverage_lymphoma-fragment_coverage-databcell_lymphomatrackdatalymph_node_lymphoma_14k_atac_fragmentstsvgz-pileup.bigwig
- data/bcell_lymphoma/trackdata/pax5/coverage_macrophage-fragment_coverage-databcell_lymphomatrackdatalymph_node_lymphoma_14k_atac_fragmentstsvgz-pileup.bigwig
- data/bcell_lymphoma/trackdata/pax5/coverage_t_cell-fragment_coverage-databcell_lymphomatrackdatalymph_node_lymphoma_14k_atac_fragmentstsvgz-pileup.bigwig
- data/bcell_lymphoma/trackdata/pax5/factorhits_46138-bed-none-bed.bed
- data/bcell_lymphoma/trackdata/pax5/factorhits_51245-bed-none-bed.bed
- data/bcell_lymphoma/trackdata/pax5/factorhits_59437-bed-none-bed.bed
