name: kladi
channels:
  - conda-forge
  - bioconda
  - liulab-dfci
  - pytorch
dependencies:
  - python>=3.5,<3.8
  - pytorch==1.8.0
  - tqdm
  - moods>=1.9.4.1
  - plotly>=4.1,<5
  - pyfaidx>=0.5,<1
  - matplotlib>=3.4,<4
  - lisa2>=2.2.5,<2.3
  - requests>=2,<3
  - leidenalg
  - pyro-ppl>=1.5.2,<2
  - networkx>=2.3,<3
  - numpy>=1.19.0,<2
  - scipy>=1.5,<2
  - umap-learn>=0.5,<1