name: kladi
channels:
  - conda-forge
  - liulab-dfci
  - bioconda
  - pytorch
dependencies:
  - python>=3.5,<3.8
  - pytorch>=1.8.0
  - tqdm
  - numpy>=1.19,<2
  - scipy>=1.5,<2
  - lisa2>=2.2.5,<2.3
  - moods>=1.9.4.1
  - plotly>=4.14.3,<5,
  - pyfaidx>=0.5,<1
  - matplotlib>=3.4,<4
  - pip
  - pip:
    - pyro-ppl>=1.5.2,<2